[package]
name = "bindings"
version = "0.1.0"
edition = "2018"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
windows = "0.32.0"

[build-dependencies]
windows = "0.32.0"
